wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: huggingface
    huggingface_version: 4.20.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.10
    start_time: 1657610899
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 7
      - 23
      4: 3.8.10
      5: 0.12.20
      6: 4.20.1
      8:
      - 5
